/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframe;

import java.util.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


 // File : Gui4.java
 // Deskripsi : Praktikum Proyek 4 - Menyimpan ke dan mengambil dari List, Set, dan Map
 // @author Imam Alfarezel

public class Gui4 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Gui4.class.getName());
    
    // Deklarasi Model untuk JList agar bisa dimanipulasi datanya
    private DefaultListModel<String> dlm;
    
    // Deklarasi Collection untuk menampung data sesuai Proyek 4
    private List<String> daftarList;
    private Set<String> daftarSet;
    private Map<String, String> daftarMap;

    public Gui4() {
        initComponents();
        
        // Inisialisasi Model dan pasang ke JList
        this.dlm = new DefaultListModel<>();
        jList1.setModel(dlm);
        
        // Inisialisasi struktur data Collection
        this.daftarList = new ArrayList<>();
        this.daftarSet = new HashSet<>();
        this.daftarMap = new HashMap<>();
        
        // Mengosongkan JTextField di awal program berjalan
        jTextField1.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jSaveToListButton = new javax.swing.JButton();
        jInsertDataListButton = new javax.swing.JButton();
        jSaveToSetButton = new javax.swing.JButton();
        jInsertDataSetButton = new javax.swing.JButton();
        jSaveToMapButton = new javax.swing.JButton();
        jInsertDataMapButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jClearAllButton = new javax.swing.JButton();
        jAddButton = new javax.swing.JButton();
        jUpdateButton = new javax.swing.JButton();
        jDeleteButton = new javax.swing.JButton();
        jiItemNameLabel = new javax.swing.JLabel();
        jDataTersimpanLabel = new javax.swing.JLabel();
        jDataTersimpanLabel2 = new javax.swing.JLabel();
        jDataTersimpanLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jSaveToListButton.setText("save to list ->");
        jSaveToListButton.addActionListener(this::jSaveToListButtonActionPerformed);

        jInsertDataListButton.setText("<- insert data list");
        jInsertDataListButton.setActionCommand("jInsertDataListButton");
        jInsertDataListButton.addActionListener(this::jInsertDataListButtonActionPerformed);

        jSaveToSetButton.setText(" save to set ->");
        jSaveToSetButton.addActionListener(this::jSaveToSetButtonActionPerformed);

        jInsertDataSetButton.setText("<- insert data set");
        jInsertDataSetButton.addActionListener(this::jInsertDataSetButtonActionPerformed);

        jSaveToMapButton.setText("save to map ->");
        jSaveToMapButton.addActionListener(this::jSaveToMapButtonActionPerformed);

        jInsertDataMapButton.setText("<- insert data map");
        jInsertDataMapButton.addActionListener(this::jInsertDataMapButtonActionPerformed);

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jClearAllButton.setText("clear all");
        jClearAllButton.addActionListener(this::jClearAllButtonActionPerformed);

        jAddButton.setText("add");
        jAddButton.addActionListener(this::jAddButtonActionPerformed);

        jUpdateButton.setText("update");
        jUpdateButton.addActionListener(this::jUpdateButtonActionPerformed);

        jDeleteButton.setText("delete");
        jDeleteButton.addActionListener(this::jDeleteButtonActionPerformed);

        jiItemNameLabel.setText("item name : ");

        jDataTersimpanLabel.setText("data tersimpan : ");

        jDataTersimpanLabel2.setText("data tersimpan :");

        jDataTersimpanLabel3.setText("data tersimpan :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jClearAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jAddButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jUpdateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDeleteButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSaveToListButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDataTersimpanLabel))
                    .addComponent(jInsertDataListButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSaveToSetButton)
                        .addGap(18, 18, 18)
                        .addComponent(jDataTersimpanLabel2))
                    .addComponent(jInsertDataSetButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSaveToMapButton)
                        .addGap(18, 18, 18)
                        .addComponent(jDataTersimpanLabel3))
                    .addComponent(jInsertDataMapButton)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jiItemNameLabel))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSaveToListButton)
                            .addComponent(jDataTersimpanLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jInsertDataListButton)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSaveToSetButton)
                            .addComponent(jDataTersimpanLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jInsertDataSetButton)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSaveToMapButton)
                            .addComponent(jDataTersimpanLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jInsertDataMapButton)
                        .addGap(18, 18, 18)
                        .addComponent(jiItemNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jClearAllButton)
                    .addComponent(jAddButton)
                    .addComponent(jUpdateButton)
                    .addComponent(jDeleteButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here
        jAddButtonActionPerformed(evt);
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jSaveToSetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveToSetButtonActionPerformed
        // TODO add your handling code here:
        daftarSet.clear();
        for (int i = 0; i < dlm.getSize(); i++) {
            daftarSet.add(dlm.getElementAt(i));
        }
        jDataTersimpanLabel2.setText("Data tersimpan = " + daftarSet.size());
    }//GEN-LAST:event_jSaveToSetButtonActionPerformed

    private void jSaveToListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveToListButtonActionPerformed
        // TODO add your handling code here:
        daftarList.clear(); 
        for (int i = 0; i < dlm.getSize(); i++) {
            daftarList.add(dlm.getElementAt(i));
        }
        jDataTersimpanLabel.setText("Data tersimpan = " + daftarList.size());
    }//GEN-LAST:event_jSaveToListButtonActionPerformed

    private void jInsertDataListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertDataListButtonActionPerformed
        // TODO add your handling code here:
        dlm.clear();
        for (String item : daftarList) {
            dlm.addElement(item);
        }
    }//GEN-LAST:event_jInsertDataListButtonActionPerformed

    private void jInsertDataSetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertDataSetButtonActionPerformed
        // TODO add your handling code here:
        dlm.clear();
        for (String item : daftarSet) {
            dlm.addElement(item);
        }
    }//GEN-LAST:event_jInsertDataSetButtonActionPerformed

    private void jAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddButtonActionPerformed
        // TODO add your handling code here:
        String item = jTextField1.getText().trim();
        if (!item.isEmpty()) {
            dlm.addElement(item);
            jTextField1.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Item name tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jAddButtonActionPerformed

    private void jClearAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearAllButtonActionPerformed
        // TODO add your handling code here:
        dlm.clear();
        jTextField1.setText("");
    }//GEN-LAST:event_jClearAllButtonActionPerformed

    private void jDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteButtonActionPerformed
        // TODO add your handling code here:
        int selectedIndex = jList1.getSelectedIndex();
        if (selectedIndex != -1) {
            dlm.remove(selectedIndex);
            jTextField1.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Pilih item di daftar terlebih dahulu untuk di-delete!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jDeleteButtonActionPerformed

    private void jUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateButtonActionPerformed
        // TODO add your handling code here:
        int selectedIndex = jList1.getSelectedIndex();
        String itemBaru = jTextField1.getText().trim();
        
        if (selectedIndex != -1) {
            if (!itemBaru.isEmpty()) {
                dlm.set(selectedIndex, itemBaru);
                jTextField1.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Item name baru tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih item di daftar terlebih dahulu untuk di-update!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jUpdateButtonActionPerformed

    private void jSaveToMapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveToMapButtonActionPerformed
        // TODO add your handling code here:
        daftarMap.clear();
        for (int i = 0; i < dlm.getSize(); i++) {
            String item = dlm.getElementAt(i);
            daftarMap.put(item, item); 
        }
        jDataTersimpanLabel3.setText("Data tersimpan = " + daftarMap.size());
    }//GEN-LAST:event_jSaveToMapButtonActionPerformed

    private void jInsertDataMapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertDataMapButtonActionPerformed
        // TODO add your handling code here:
        dlm.clear();
        for (String item : daftarMap.keySet()) {
            dlm.addElement(item);
        }
    }//GEN-LAST:event_jInsertDataMapButtonActionPerformed

    /**
     * @param args the command line arguments
         java.awt.EventQueue.invokeLater(() -> new Gui4().setVisible(true));
    }   */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Gui4().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddButton;
    private javax.swing.JButton jClearAllButton;
    private javax.swing.JLabel jDataTersimpanLabel;
    private javax.swing.JLabel jDataTersimpanLabel2;
    private javax.swing.JLabel jDataTersimpanLabel3;
    private javax.swing.JButton jDeleteButton;
    private javax.swing.JButton jInsertDataListButton;
    private javax.swing.JButton jInsertDataMapButton;
    private javax.swing.JButton jInsertDataSetButton;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jSaveToListButton;
    private javax.swing.JButton jSaveToMapButton;
    private javax.swing.JButton jSaveToSetButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jUpdateButton;
    private javax.swing.JLabel jiItemNameLabel;
    // End of variables declaration//GEN-END:variables
}
