/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jdbc.program;

import java.util.*;
import java.sql.*;
import javax.swing.DefaultListModel;
import jdbc.model.*;
import jdbc.service.*;
import jdbc.program.*;

/**
 * File : JFrameUtama.java
 * Deskripsi : GUI untuk mengelola data mahasiswa terintegrasi dengan database
 * @author Imam Alfarezel
 */

public class JFrameUtama extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameUtama.class.getName());

    MysqlMahasiswaService service = new MysqlMahasiswaService();
    
    /**
     * Creates new form JFrameUtama
     */
    public JFrameUtama() {
        initComponents();
        jList1.setModel(new DefaultListModel<>());
        jList2.setModel(new DefaultListModel<>());
        
        jList1.addListSelectionListener(e -> {
            int index = jList1.getSelectedIndex();
            if (index >= 0) {
                jList2.setSelectedIndex(index);
                jIDEditTextField1.setText(((DefaultListModel<String>) jList1.getModel()).getElementAt(index));
                jNamaEditTextField1.setText(((DefaultListModel<String>) jList2.getModel()).getElementAt(index));
                jIDHapusTextField.setText(((DefaultListModel<String>) jList1.getModel()).getElementAt(index));
                jNamaHapusTextField.setText(((DefaultListModel<String>) jList2.getModel()).getElementAt(index));
            }
        });

        jList2.addListSelectionListener(e -> {
            int index = jList2.getSelectedIndex();
            if (index >= 0) {
                jList1.setSelectedIndex(index);
                jIDEditTextField1.setText(((DefaultListModel<String>) jList1.getModel()).getElementAt(index));
                jNamaEditTextField1.setText(((DefaultListModel<String>) jList2.getModel()).getElementAt(index));
                jIDHapusTextField.setText(((DefaultListModel<String>) jList1.getModel()).getElementAt(index));
                jNamaHapusTextField.setText(((DefaultListModel<String>) jList2.getModel()).getElementAt(index));
            }
        });
        
        jAmbilSemuaDataButtonActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jAmbilSemuaDataButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jNamaTambahkanTextField1 = new javax.swing.JTextField();
        jTambahkanButton = new javax.swing.JButton();
        jIDEditTextField1 = new javax.swing.JTextField();
        jNamaEditTextField1 = new javax.swing.JTextField();
        jEditButton1 = new javax.swing.JButton();
        jIDHapusTextField = new javax.swing.JTextField();
        jNamaHapusTextField = new javax.swing.JTextField();
        jHapusButton = new javax.swing.JButton();
        jResetIndeksButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jLabel1.setText("Kelola Data Mahasiswa");

        jAmbilSemuaDataButton.setText("ambil semua data");
        jAmbilSemuaDataButton.addActionListener(this::jAmbilSemuaDataButtonActionPerformed);

        jLabel2.setText("Nama : ");

        jTambahkanButton.setText("Tambahkan");
        jTambahkanButton.addActionListener(this::jTambahkanButtonActionPerformed);

        jIDEditTextField1.addActionListener(this::jIDEditTextField1ActionPerformed);

        jNamaEditTextField1.addActionListener(this::jNamaEditTextField1ActionPerformed);

        jEditButton1.setText("edit");
        jEditButton1.addActionListener(this::jEditButton1ActionPerformed);

        jIDHapusTextField.addActionListener(this::jIDHapusTextFieldActionPerformed);

        jNamaHapusTextField.addActionListener(this::jNamaHapusTextFieldActionPerformed);

        jHapusButton.setText("hapus");
        jHapusButton.addActionListener(this::jHapusButtonActionPerformed);

        jResetIndeksButton.setText("reset indeks");
        jResetIndeksButton.addActionListener(this::jResetIndeksButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTambahkanButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jAmbilSemuaDataButton)
                        .addComponent(jNamaTambahkanTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jIDHapusTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jIDEditTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jNamaEditTextField1)
                            .addComponent(jNamaHapusTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jEditButton1)
                            .addComponent(jHapusButton)))
                    .addComponent(jResetIndeksButton))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(109, 109, 109))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jAmbilSemuaDataButton)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jNamaTambahkanTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTambahkanButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jIDEditTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jNamaEditTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEditButton1))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jIDHapusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jNamaHapusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jHapusButton))
                        .addGap(18, 18, 18)
                        .addComponent(jResetIndeksButton)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAmbilSemuaDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAmbilSemuaDataButtonActionPerformed
        // TODO add your handling code here:
        DefaultListModel<String> idModel = new DefaultListModel<>();
        DefaultListModel<String> nameModel = new DefaultListModel<>();
    
        List<Mahasiswa> list = service.getAll();
        for (Mahasiswa mhs : list) {
            idModel.addElement(String.valueOf(mhs.getId()));
            nameModel.addElement(mhs.getNama());
        }
        jList1.setModel(idModel);
        jList2.setModel(nameModel);
    }//GEN-LAST:event_jAmbilSemuaDataButtonActionPerformed

    private void jTambahkanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTambahkanButtonActionPerformed
        // TODO add your handling code here:
        String nama = jNamaTambahkanTextField1.getText();
        if(nama.trim().isEmpty()) return;
        
        // Menggunakan pencarian ID maksimal manual agar klop dengan database non-auto increment
        int nextId = 1;
        List<Mahasiswa> list = service.getAll();
        for (Mahasiswa mhs : list) {
            if (mhs.getId() >= nextId) {
                nextId = mhs.getId() + 1;
            }
        }
        
        service.add(new Mahasiswa(nextId, nama));
        jAmbilSemuaDataButton.doClick();
        jNamaTambahkanTextField1.setText("");
    }//GEN-LAST:event_jTambahkanButtonActionPerformed

    private void jIDEditTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIDEditTextField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jIDEditTextField1ActionPerformed

    private void jNamaEditTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNamaEditTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNamaEditTextField1ActionPerformed

    private void jEditButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditButton1ActionPerformed
        // TODO add your handling code here:
        if(jIDEditTextField1.getText().isEmpty() || jNamaEditTextField1.getText().isEmpty()){ return; }
        int id = Integer.parseInt(jIDEditTextField1.getText());
        String nama = jNamaEditTextField1.getText();
        service.update(new Mahasiswa(id, nama));
        jAmbilSemuaDataButton.doClick();
        
        jIDEditTextField1.setText(""); jNamaEditTextField1.setText("");
        jIDHapusTextField.setText(""); jNamaHapusTextField.setText("");
    }//GEN-LAST:event_jEditButton1ActionPerformed

    private void jIDHapusTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIDHapusTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIDHapusTextFieldActionPerformed

    private void jNamaHapusTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNamaHapusTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNamaHapusTextFieldActionPerformed

    private void jHapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHapusButtonActionPerformed
        // TODO add your handling code here:
        if(jIDHapusTextField.getText().isEmpty() || jNamaHapusTextField.getText().isEmpty()){ return; }
        int id = Integer.parseInt(jIDHapusTextField.getText());
        service.delete(id);
        jAmbilSemuaDataButton.doClick();
        
        jIDHapusTextField.setText(""); jNamaHapusTextField.setText("");
        jIDEditTextField1.setText(""); jNamaEditTextField1.setText("");
    }//GEN-LAST:event_jHapusButtonActionPerformed

    private void jResetIndeksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetIndeksButtonActionPerformed
        // TODO add your handling code here:
        jNamaTambahkanTextField1.setText("");
        jIDEditTextField1.setText("");
        jNamaEditTextField1.setText("");
        jIDHapusTextField.setText("");
        jNamaHapusTextField.setText("");
        jList1.clearSelection();
        jList2.clearSelection();
    }//GEN-LAST:event_jResetIndeksButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameUtama().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAmbilSemuaDataButton;
    private javax.swing.JButton jEditButton1;
    private javax.swing.JButton jHapusButton;
    private javax.swing.JTextField jIDEditTextField1;
    private javax.swing.JTextField jIDHapusTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JTextField jNamaEditTextField1;
    private javax.swing.JTextField jNamaHapusTextField;
    private javax.swing.JTextField jNamaTambahkanTextField1;
    private javax.swing.JButton jResetIndeksButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jTambahkanButton;
    // End of variables declaration//GEN-END:variables
}
